### ISSUE TITLE
CBM implementation 

### ISSUE THREAD

**Issue by antoyang** [m-bain/CondensedMovies#3]
Hi,

Thanks for your great work. It looks like the CBM part of your method isn't implemented in this repo, do you plan to release it anytime soon?

Best,
Antoine Yang

**Comment by varungupta31** [comment]
Hey @antoyang, I see you closed the issue but the code for CBM wasn't included in the repo. Did you find or write the code? Thanks.

**Comment by antoyang** [comment]
Hi, I did not.
