### ISSUE TITLE
Plot Synopses Annotations

### ISSUE THREAD

**Issue by zjuchenlong** [m-bain/CondensedMovies#6]
Hi, 

I just download the dataset, but I can not find the Wikipedia/IMDB plot synopses and alignment annotations. Where can I download these annotations?

Best,
Long

**Comment by jeripothula-prudviraj** [comment]
I'm also looking for it. Pls let me know if you find it

**Comment by m-bain** [comment]
`wget https://www.robots.ox.ac.uk/~vgg/data/condensed-movies/assets/plots_wiki.csv`
`wget https://www.robots.ox.ac.uk/~vgg/data/condensed-movies/assets/plots_imdb.csv`

**Comment by fazlicodes** [comment]
@m-bain where can I get the captions/annotations for the dataset?
